micronaut:
  application:
    name: backend
  server:
    cors:
      enabled: true

      configurations:
        web:
          allowed-origins-regex: 'http://127.0.0.1:3000'

mongo:
  uri: mongodb://localhost:27017/teams?minPoolSize=12&maxPoolSize=12&authSource=admin
  database: teams

